-- Snowflake load script generated by gen_retail_dw.py
-- Run order: (1) this context block  (2) schema.sql  (3) the rest of this file.
-- PUT only works from SnowSQL / Snowflake CLI / a connector, not from Snowsight worksheets.

CREATE DATABASE IF NOT EXISTS RETAIL_DW;
CREATE SCHEMA IF NOT EXISTS RETAIL_DW.CORE;
USE SCHEMA RETAIL_DW.CORE;

CREATE OR REPLACE FILE FORMAT retail_csv
  TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"' EMPTY_FIELD_AS_NULL = TRUE
  DATE_FORMAT = 'YYYY-MM-DD' TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS' ENCODING = 'UTF8';
CREATE OR REPLACE STAGE retail_stage FILE_FORMAT = retail_csv;

PUT 'file://C:/Users/AgnitChatterjee/Documents/Project_Me/AI_Self_Project/Learn-AI/retail_dw/*.csv' @retail_stage AUTO_COMPRESS = TRUE OVERWRITE = TRUE;

-- Dimensions first, then facts (same order as schema.sql)
COPY INTO dim_date FROM @retail_stage/dim_date.csv.gz ON_ERROR = ABORT_STATEMENT;
COPY INTO dim_supplier FROM @retail_stage/dim_supplier.csv.gz ON_ERROR = ABORT_STATEMENT;
COPY INTO dim_product FROM @retail_stage/dim_product.csv.gz ON_ERROR = ABORT_STATEMENT;
COPY INTO dim_customer FROM @retail_stage/dim_customer.csv.gz ON_ERROR = ABORT_STATEMENT;
COPY INTO dim_store FROM @retail_stage/dim_store.csv.gz ON_ERROR = ABORT_STATEMENT;
COPY INTO dim_promotion FROM @retail_stage/dim_promotion.csv.gz ON_ERROR = ABORT_STATEMENT;
COPY INTO fact_sales FROM @retail_stage/fact_sales.csv.gz ON_ERROR = ABORT_STATEMENT;
COPY INTO fact_returns FROM @retail_stage/fact_returns.csv.gz ON_ERROR = ABORT_STATEMENT;
COPY INTO fact_product_reviews FROM @retail_stage/fact_product_reviews.csv.gz ON_ERROR = ABORT_STATEMENT;
COPY INTO fact_inventory_snapshot FROM @retail_stage/fact_inventory_snapshot.csv.gz ON_ERROR = ABORT_STATEMENT;
COPY INTO fact_purchase_orders FROM @retail_stage/fact_purchase_orders.csv.gz ON_ERROR = ABORT_STATEMENT;

-- Self-check: loaded vs expected row counts
SELECT 'dim_date' AS tbl, (SELECT COUNT(*) FROM dim_date) AS loaded, 1489 AS expected
UNION ALL
SELECT 'dim_supplier' AS tbl, (SELECT COUNT(*) FROM dim_supplier) AS loaded, 25 AS expected
UNION ALL
SELECT 'dim_product' AS tbl, (SELECT COUNT(*) FROM dim_product) AS loaded, 300 AS expected
UNION ALL
SELECT 'dim_customer' AS tbl, (SELECT COUNT(*) FROM dim_customer) AS loaded, 2260 AS expected
UNION ALL
SELECT 'dim_store' AS tbl, (SELECT COUNT(*) FROM dim_store) AS loaded, 14 AS expected
UNION ALL
SELECT 'dim_promotion' AS tbl, (SELECT COUNT(*) FROM dim_promotion) AS loaded, 54 AS expected
UNION ALL
SELECT 'fact_sales' AS tbl, (SELECT COUNT(*) FROM fact_sales) AS loaded, 58293 AS expected
UNION ALL
SELECT 'fact_returns' AS tbl, (SELECT COUNT(*) FROM fact_returns) AS loaded, 3585 AS expected
UNION ALL
SELECT 'fact_product_reviews' AS tbl, (SELECT COUNT(*) FROM fact_product_reviews) AS loaded, 1919 AS expected
UNION ALL
SELECT 'fact_inventory_snapshot' AS tbl, (SELECT COUNT(*) FROM fact_inventory_snapshot) AS loaded, 37440 AS expected
UNION ALL
SELECT 'fact_purchase_orders' AS tbl, (SELECT COUNT(*) FROM fact_purchase_orders) AS loaded, 344 AS expected;
