-- Generated by gen_retail_dw.py (ANSI-style; works on Snowflake, Databricks SQL, Postgres, SQLite)

CREATE TABLE IF NOT EXISTS dim_date (
    date_key INTEGER,
    full_date DATE,
    day_of_week SMALLINT,
    day_name VARCHAR(10),
    day_of_month SMALLINT,
    week_of_year SMALLINT,
    month_num SMALLINT,
    month_name VARCHAR(10),
    quarter SMALLINT,
    year SMALLINT,
    fiscal_year SMALLINT,
    fiscal_quarter SMALLINT,
    is_weekend SMALLINT,
    is_holiday SMALLINT,
    is_peak_season SMALLINT,
    PRIMARY KEY (date_key)
);

CREATE TABLE IF NOT EXISTS dim_supplier (
    supplier_key INTEGER,
    supplier_name VARCHAR(100),
    country VARCHAR(50),
    lead_time_days SMALLINT,
    payment_terms VARCHAR(20),
    quality_rating DECIMAL(3,1),
    contract_start_date DATE,
    PRIMARY KEY (supplier_key)
);

CREATE TABLE IF NOT EXISTS dim_product (
    product_key INTEGER,
    sku VARCHAR(20),
    product_name VARCHAR(150),
    department VARCHAR(50),
    category VARCHAR(50),
    subcategory VARCHAR(50),
    brand VARCHAR(50),
    supplier_key INTEGER,
    list_price DECIMAL(12,2),
    unit_cost DECIMAL(12,2),
    description VARCHAR(2000),
    attributes_json VARCHAR(500),
    launch_date DATE,
    discontinued_date DATE,
    is_active SMALLINT,
    PRIMARY KEY (product_key),
    FOREIGN KEY (supplier_key) REFERENCES dim_supplier(supplier_key)
);

CREATE TABLE IF NOT EXISTS dim_customer (
    customer_key INTEGER,
    customer_id VARCHAR(12),
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    email VARCHAR(120),
    gender VARCHAR(10),
    birth_date DATE,
    city VARCHAR(50),
    state VARCHAR(50),
    country VARCHAR(50),
    loyalty_tier VARCHAR(10),
    signup_date DATE,
    acquisition_channel VARCHAR(30),
    effective_from DATE,
    effective_to DATE,
    is_current SMALLINT,
    PRIMARY KEY (customer_key)
);

CREATE TABLE IF NOT EXISTS dim_store (
    store_key INTEGER,
    store_id VARCHAR(10),
    store_name VARCHAR(100),
    store_type VARCHAR(20),
    channel VARCHAR(10),
    city VARCHAR(50),
    state VARCHAR(50),
    country VARCHAR(50),
    region VARCHAR(20),
    open_date DATE,
    square_feet INTEGER,
    manager_name VARCHAR(100),
    PRIMARY KEY (store_key)
);

CREATE TABLE IF NOT EXISTS dim_promotion (
    promo_key INTEGER,
    promo_name VARCHAR(100),
    promo_type VARCHAR(20),
    discount_pct DECIMAL(5,2),
    start_date DATE,
    end_date DATE,
    channel VARCHAR(10),
    target_department VARCHAR(50),
    PRIMARY KEY (promo_key)
);

CREATE TABLE IF NOT EXISTS fact_sales (
    sales_line_key BIGINT,
    order_id VARCHAR(14),
    line_number SMALLINT,
    date_key INTEGER,
    order_timestamp TIMESTAMP,
    product_key INTEGER,
    customer_key INTEGER,
    store_key INTEGER,
    promo_key INTEGER,
    payment_method VARCHAR(20),
    quantity SMALLINT,
    unit_price DECIMAL(12,2),
    discount_amount DECIMAL(12,2),
    net_sales DECIMAL(12,2),
    tax_amount DECIMAL(12,2),
    cost_amount DECIMAL(12,2),
    gross_margin DECIMAL(12,2),
    PRIMARY KEY (sales_line_key),
    FOREIGN KEY (date_key) REFERENCES dim_date(date_key),
    FOREIGN KEY (product_key) REFERENCES dim_product(product_key),
    FOREIGN KEY (customer_key) REFERENCES dim_customer(customer_key),
    FOREIGN KEY (store_key) REFERENCES dim_store(store_key),
    FOREIGN KEY (promo_key) REFERENCES dim_promotion(promo_key)
);

CREATE TABLE IF NOT EXISTS fact_returns (
    return_key BIGINT,
    sales_line_key BIGINT,
    order_id VARCHAR(14),
    date_key INTEGER,
    product_key INTEGER,
    customer_key INTEGER,
    store_key INTEGER,
    quantity_returned SMALLINT,
    refund_amount DECIMAL(12,2),
    reason_code VARCHAR(30),
    item_condition VARCHAR(20),
    customer_comment VARCHAR(500),
    PRIMARY KEY (return_key),
    FOREIGN KEY (sales_line_key) REFERENCES fact_sales(sales_line_key),
    FOREIGN KEY (date_key) REFERENCES dim_date(date_key),
    FOREIGN KEY (product_key) REFERENCES dim_product(product_key),
    FOREIGN KEY (customer_key) REFERENCES dim_customer(customer_key),
    FOREIGN KEY (store_key) REFERENCES dim_store(store_key)
);

CREATE TABLE IF NOT EXISTS fact_product_reviews (
    review_key BIGINT,
    sales_line_key BIGINT,
    product_key INTEGER,
    customer_key INTEGER,
    date_key INTEGER,
    rating SMALLINT,
    review_title VARCHAR(150),
    review_text VARCHAR(2000),
    helpful_votes INTEGER,
    verified_purchase SMALLINT,
    PRIMARY KEY (review_key),
    FOREIGN KEY (sales_line_key) REFERENCES fact_sales(sales_line_key),
    FOREIGN KEY (product_key) REFERENCES dim_product(product_key),
    FOREIGN KEY (customer_key) REFERENCES dim_customer(customer_key),
    FOREIGN KEY (date_key) REFERENCES dim_date(date_key)
);

CREATE TABLE IF NOT EXISTS fact_inventory_snapshot (
    snapshot_date_key INTEGER,
    product_key INTEGER,
    store_key INTEGER,
    on_hand_qty INTEGER,
    units_sold_week INTEGER,
    reorder_point INTEGER,
    stockout_flag SMALLINT,
    inventory_value DECIMAL(14,2),
    PRIMARY KEY (snapshot_date_key, product_key, store_key),
    FOREIGN KEY (snapshot_date_key) REFERENCES dim_date(date_key),
    FOREIGN KEY (product_key) REFERENCES dim_product(product_key),
    FOREIGN KEY (store_key) REFERENCES dim_store(store_key)
);

CREATE TABLE IF NOT EXISTS fact_purchase_orders (
    po_key BIGINT,
    po_number VARCHAR(12),
    supplier_key INTEGER,
    product_key INTEGER,
    store_key INTEGER,
    order_date_key INTEGER,
    expected_date_key INTEGER,
    received_date_key INTEGER,
    qty_ordered INTEGER,
    qty_received INTEGER,
    unit_cost DECIMAL(12,2),
    status VARCHAR(12),
    PRIMARY KEY (po_key),
    FOREIGN KEY (supplier_key) REFERENCES dim_supplier(supplier_key),
    FOREIGN KEY (product_key) REFERENCES dim_product(product_key),
    FOREIGN KEY (store_key) REFERENCES dim_store(store_key),
    FOREIGN KEY (order_date_key) REFERENCES dim_date(date_key),
    FOREIGN KEY (expected_date_key) REFERENCES dim_date(date_key),
    FOREIGN KEY (received_date_key) REFERENCES dim_date(date_key)
);
