-- Snowflake load script generated by gen_enterprise_data.py
-- Run order: (1) this context block  (2) schema.sql  (3) the rest of this file.
-- PUT only works from SnowSQL / Snowflake CLI / a connector, not from Snowsight worksheets.

CREATE DATABASE IF NOT EXISTS ENTERPRISE_KB;
CREATE SCHEMA IF NOT EXISTS ENTERPRISE_KB.RAW;
USE SCHEMA ENTERPRISE_KB.RAW;

-- Document bodies contain newlines and quotes, so quoted-field handling is required.
CREATE OR REPLACE FILE FORMAT ent_csv
  TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"' EMPTY_FIELD_AS_NULL = TRUE
  DATE_FORMAT = 'YYYY-MM-DD' TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS' ENCODING = 'UTF8';
CREATE OR REPLACE STAGE ent_stage FILE_FORMAT = ent_csv;

PUT 'file://C:/Users/AgnitChatterjee/Documents/Project_Me/AI_Self_Project/Learn-AI/enterprise_data/*.csv' @ent_stage AUTO_COMPRESS = TRUE OVERWRITE = TRUE;

COPY INTO departments FROM @ent_stage/departments.csv.gz ON_ERROR = ABORT_STATEMENT;
COPY INTO employees FROM @ent_stage/employees.csv.gz ON_ERROR = ABORT_STATEMENT;
COPY INTO projects FROM @ent_stage/projects.csv.gz ON_ERROR = ABORT_STATEMENT;
COPY INTO project_members FROM @ent_stage/project_members.csv.gz ON_ERROR = ABORT_STATEMENT;
COPY INTO services FROM @ent_stage/services.csv.gz ON_ERROR = ABORT_STATEMENT;
COPY INTO documents FROM @ent_stage/documents.csv.gz ON_ERROR = ABORT_STATEMENT;
COPY INTO document_versions FROM @ent_stage/document_versions.csv.gz ON_ERROR = ABORT_STATEMENT;
COPY INTO document_acl FROM @ent_stage/document_acl.csv.gz ON_ERROR = ABORT_STATEMENT;
COPY INTO emails FROM @ent_stage/emails.csv.gz ON_ERROR = ABORT_STATEMENT;
COPY INTO tickets FROM @ent_stage/tickets.csv.gz ON_ERROR = ABORT_STATEMENT;
COPY INTO eval_queries FROM @ent_stage/eval_queries.csv.gz ON_ERROR = ABORT_STATEMENT;
COPY INTO eval_qrels FROM @ent_stage/eval_qrels.csv.gz ON_ERROR = ABORT_STATEMENT;
COPY INTO query_log FROM @ent_stage/query_log.csv.gz ON_ERROR = ABORT_STATEMENT;

-- Self-check: loaded vs expected row counts
SELECT 'departments' AS tbl, (SELECT COUNT(*) FROM departments) AS loaded, 11 AS expected
UNION ALL
SELECT 'employees' AS tbl, (SELECT COUNT(*) FROM employees) AS loaded, 200 AS expected
UNION ALL
SELECT 'projects' AS tbl, (SELECT COUNT(*) FROM projects) AS loaded, 30 AS expected
UNION ALL
SELECT 'project_members' AS tbl, (SELECT COUNT(*) FROM project_members) AS loaded, 188 AS expected
UNION ALL
SELECT 'services' AS tbl, (SELECT COUNT(*) FROM services) AS loaded, 20 AS expected
UNION ALL
SELECT 'documents' AS tbl, (SELECT COUNT(*) FROM documents) AS loaded, 300 AS expected
UNION ALL
SELECT 'document_versions' AS tbl, (SELECT COUNT(*) FROM document_versions) AS loaded, 875 AS expected
UNION ALL
SELECT 'document_acl' AS tbl, (SELECT COUNT(*) FROM document_acl) AS loaded, 369 AS expected
UNION ALL
SELECT 'emails' AS tbl, (SELECT COUNT(*) FROM emails) AS loaded, 1500 AS expected
UNION ALL
SELECT 'tickets' AS tbl, (SELECT COUNT(*) FROM tickets) AS loaded, 800 AS expected
UNION ALL
SELECT 'eval_queries' AS tbl, (SELECT COUNT(*) FROM eval_queries) AS loaded, 150 AS expected
UNION ALL
SELECT 'eval_qrels' AS tbl, (SELECT COUNT(*) FROM eval_qrels) AS loaded, 1033 AS expected
UNION ALL
SELECT 'query_log' AS tbl, (SELECT COUNT(*) FROM query_log) AS loaded, 2000 AS expected;
