-- Generated by gen_enterprise_data.py (types inferred from the data)

CREATE TABLE IF NOT EXISTS departments (
    department_id VARCHAR,
    name VARCHAR,
    head_employee_id INTEGER,
    cost_center VARCHAR
);

CREATE TABLE IF NOT EXISTS employees (
    employee_id INTEGER,
    first_name VARCHAR,
    last_name VARCHAR,
    full_name VARCHAR,
    email VARCHAR,
    department_id VARCHAR,
    title VARCHAR,
    level INTEGER,
    manager_id INTEGER,
    location_city VARCHAR,
    region VARCHAR,
    hire_date DATE,
    employment_status VARCHAR
);

CREATE TABLE IF NOT EXISTS projects (
    project_id VARCHAR,
    name VARCHAR,
    department_id VARCHAR,
    owner_id INTEGER,
    sponsor_id INTEGER,
    status VARCHAR,
    start_date DATE,
    target_date DATE,
    budget_usd INTEGER,
    priority VARCHAR
);

CREATE TABLE IF NOT EXISTS project_members (
    project_id VARCHAR,
    employee_id INTEGER,
    role VARCHAR
);

CREATE TABLE IF NOT EXISTS services (
    service_id VARCHAR,
    name VARCHAR,
    owner_employee_id INTEGER,
    owner_department_id VARCHAR,
    language VARCHAR,
    database VARCHAR,
    message_queue VARCHAR,
    tier INTEGER,
    availability_slo_pct FLOAT,
    p95_latency_ms INTEGER,
    repo_url VARCHAR
);

CREATE TABLE IF NOT EXISTS documents (
    doc_id VARCHAR,
    title VARCHAR,
    doc_type VARCHAR,
    department_id VARCHAR,
    author_id INTEGER,
    region VARCHAR,
    project_id VARCHAR,
    source_system VARCHAR,
    url VARCHAR,
    status VARCHAR,
    version INTEGER,
    confidentiality VARCHAR,
    created_at DATE,
    updated_at DATE,
    word_count INTEGER,
    body VARCHAR
);

CREATE TABLE IF NOT EXISTS document_versions (
    doc_id VARCHAR,
    version INTEGER,
    changed_by INTEGER,
    changed_at DATE,
    change_summary VARCHAR
);

CREATE TABLE IF NOT EXISTS document_acl (
    doc_id VARCHAR,
    principal_type VARCHAR,
    principal_id VARCHAR
);

CREATE TABLE IF NOT EXISTS emails (
    message_id VARCHAR,
    thread_id VARCHAR,
    sender_id INTEGER,
    to_ids VARCHAR,
    cc_ids VARCHAR,
    subject VARCHAR,
    body VARCHAR,
    sent_at TIMESTAMP,
    related_doc_id VARCHAR,
    has_attachment INTEGER,
    in_reply_to VARCHAR
);

CREATE TABLE IF NOT EXISTS tickets (
    ticket_id VARCHAR,
    category VARCHAR,
    priority VARCHAR,
    status VARCHAR,
    requester_id INTEGER,
    assignee_id INTEGER,
    created_at TIMESTAMP,
    resolved_at TIMESTAMP,
    first_response_minutes INTEGER,
    subject VARCHAR,
    description VARCHAR,
    resolution VARCHAR,
    related_doc_id VARCHAR,
    csat INTEGER
);

CREATE TABLE IF NOT EXISTS eval_queries (
    query_id VARCHAR,
    question VARCHAR,
    expected_answer VARCHAR,
    source_doc_id VARCHAR,
    doc_type VARCHAR,
    difficulty VARCHAR,
    region VARCHAR,
    hard_negative_doc_ids VARCHAR
);

CREATE TABLE IF NOT EXISTS eval_qrels (
    query_id VARCHAR,
    doc_id VARCHAR,
    relevance INTEGER
);

CREATE TABLE IF NOT EXISTS query_log (
    log_id VARCHAR,
    session_id VARCHAR,
    employee_id INTEGER,
    asked_at TIMESTAMP,
    query_text VARCHAR,
    eval_query_id VARCHAR,
    model VARCHAR,
    latency_ms INTEGER,
    prompt_tokens INTEGER,
    completion_tokens INTEGER,
    cost_usd FLOAT,
    top1_doc_id VARCHAR,
    top1_correct INTEGER,
    feedback VARCHAR,
    error INTEGER
);
